run:
  timeout: 5m

linters:
  enable:
    - errcheck
    - gosimple
    - govet
    - ineffassign
    - staticcheck
    - unused
    - goimports
    - misspell
    - gocritic
    - revive
    - unconvert
    - unparam
    - whitespace

linters-settings:
  govet:
    enable-all: true
  goimports:
    local-prefixes: github.com/kazuma-desu/etu
  misspell:
    locale: US

issues:
  exclude-rules:
    - path: _test\.go
      linters:
        - errcheck
        - gosec
  max-same-issues: 0
