version: "2"
linters:
  enable:
    - gocritic
    - misspell
    - revive
    - unconvert
    - unparam
    - whitespace
  settings:
    govet:
      enable-all: true
    misspell:
      locale: US
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    rules:
      - linters:
          - errcheck
          - gosec
        path: _test\.go
    paths:
      - third_party$
      - builtin$
      - examples$
issues:
  max-same-issues: 0
formatters:
  enable:
    - goimports
  settings:
    goimports:
      local-prefixes:
        - github.com/kazuma-desu/etu
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
